### ISSUE TITLE
Passing command line arguments to `build` or any command

### ISSUE THREAD

**Issue by coulson84** [mbtproject/mbt#118]
Is it possible to pass command line arguments when calling `mbt build` or `mbt run-in`

I am looking to use mbt for but currently we would call, for example,
`npm run dev:eap -- --DEV_API <custom host domain>` 
or to pass arguments in during a build that configure how the build executes. Is there any way to do this with mbt I couldn't see anything in the documentation that indicated it was possible?

**Comment by buddyspike** [comment]
Custom arguments are specified in `.mbt.yml`. In this instance (assuming this is your build command), you could do something like:

```
build:
  linux:
    cmd: npm
    args: ['run', 'dev:eap', '--', '--DEV_API', <custom host domain>]
```

hth
