### ISSUE TITLE
How file diffrential handle by mbt?

### ISSUE THREAD

**Issue by pratikbalar** [mbtproject/mbt#138]
Thank you for the awsome tool

I am building docker images with mbt in our monorepo and i can't understand how mbt is handling git diff thing?

This is my directory structure
```log
/
-->abc/
  -->.mbt.yml (for xyz docker image)
  --><abc image files>
-->common/
-->abc.Dockerfile
-->xyz.Dockerfile
-->xyz/
  --> <xyz image files>
-->.mbt.yml (for xyz docker image)
-->dockerbuild.sh
```
so common will be shared by both service `abc` and `xyz`

and `mbt describe branch mbt-monorepo --in . --debug`  gives me this

```bash
Name              PATH                      VERSION
xyz                                    cb05727511f395dbe071b98a85c1d82583f9e826
abc               abc               a805557e77add60a947f260549441228c50a1930
```

`/abc/.mbt.yml` contain
```yaml
name: services
# fileDependencies: ?
build:
  darwin:
    cmd: dockerbuild.sh
  linux:
    cmd: dockerbuild.sh
properties:
  NAME: abc
  DOCKERFILE: abc.Dockerfile
```

I was wondering that `fileDependencies` is giving mbt for diff references to check whether files have changed or not and on that mbt will build it? 

P.S. im using properties values for `dockerbuild.sh` to determine weather it is `abc` or `xyz` service
