### ISSUE TITLE
Supports Maven and/or Gradle (Java build tools)?

### ISSUE THREAD

**Issue by paul-hammant** [mbtproject/mbt#23]

**Comment by buddyspike** [comment]
This should already be possible. In fact one of the design goals of mbt is to be able to work with any build tool that's already out there.

For example, the root directory containing the maven project could have an `.mbt.yml` file that executes `mvn package` when executing `mbt build xxx`. 

```
name: my-java-module
build:
  darwin:
    cmd: maven
    args: [package]
```

In reality, the build could be a little bit more complicated than running `mvn package`. For those cases, you generally configure your build script in `.mbt.yml`.
