### ISSUE TITLE
Universal build command in the MBT spec file

### ISSUE THREAD

**Issue by ojizero** [mbtproject/mbt#84]
Not sure if this already exists or not, but is there a way, and if not would it make sense, to have a default version of the build command in the spec file.

What I mean is in the `.mbt.yml` file, instead of defining the build command for each platform, to define it once as a `default` command, to run on all platforms unless otherwise specified.

```yaml
# as an example something like this
name: my-module
build:
  default: # regardless of the platform, run this command on build
    cmd: some-platform-agnostic-command
```

This could be useful in case there's no need to specify the same build command for multiple platforms, think of an NPM run script for example as it's platform independent in many cases as an example.

It could potentially offer a way to override it for specific platforms, for example if there's a custom build ran on Linux for any platform specific reason,

```yaml
name: my-module
build:
  default: # runs on any system
    cmd: my-generic-command
  linux: # runs if the system is linux based
    cmd: a-linux-specific-build-script
```

**Comment by buddyspike** [comment]
Good question. This facility is currently not available in `build xxx` commands. However, we introduced a user defined commands feature that has this feature.
It's not well documented at the moment, but you will get the gist of it here:
https://github.com/mbtproject/mbt#user-defined-commands

You basically run it like this:
 `run-in diff|branch|head|local|pr|commit --command <command name>` 

User defined commands have a property called `os` where you can ***optionally*** specify os restrictions.
e.g.
```
commands:
  hello:
    cmd: echo
    args: [hello]
    os: [darwin, linux]
```

We would like to port this functionality to build command as well. Alternatively, if everyone is finding user defined commands as a more flexible way to define them, we could start deprecating `build` command.
